FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy prisma schema
COPY src/infrastructure/database/prisma ./src/infrastructure/database/prisma

# Generate Prisma Client
RUN npx prisma generate --schema=./src/infrastructure/database/prisma/schema.prisma

# Copy source code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
