export enum UserRole {
  CLIENT = 'CLIENT',
  SUPPLIER_FOOD = 'SUPPLIER_FOOD',
  SUPPLIER_DEALS = 'SUPPLIER_DEALS',
  ASSOCIATION = 'ASSOCIATION',
  ADVERTISER = 'ADVERTISER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum UserStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum SupplierType {
  RESTAURANT = 'RESTAURANT',
  BAKERY = 'BAKERY',
  PASTRY_SHOP = 'PASTRY_SHOP',
  SUPERMARKET = 'SUPERMARKET',
  HOTEL = 'HOTEL',
  LEISURE = 'LEISURE',
  BEAUTY = 'BEAUTY',
  TRANSPORT = 'TRANSPORT',
  OTHER = 'OTHER',
}

export enum SubscriptionTier {
  BASIC = 'BASIC',
  PRO = 'PRO',
  PREMIUM = 'PREMIUM',
}

export enum ProductCategory {
  BAKERY_PASTRY = 'BAKERY_PASTRY',
  GROCERY_BASKET = 'GROCERY_BASKET',
  INTERNATIONAL_CUISINE = 'INTERNATIONAL_CUISINE',
  LOCAL_TRADITIONAL = 'LOCAL_TRADITIONAL',
  RESTAURANT = 'RESTAURANT',
  PREPARED_MEALS_INDIVIDUAL = 'PREPARED_MEALS_INDIVIDUAL',
  MEAT_FISH = 'MEAT_FISH',
  OTHER = 'OTHER',
}

export enum ProductStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  SOLD_OUT = 'SOLD_OUT',
  EXPIRED = 'EXPIRED',
  ARCHIVED = 'ARCHIVED',
}

export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID = 'PAID',
  PREPARING = 'PREPARING',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  IN_DELIVERY = 'IN_DELIVERY',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum DeliveryMethod {
  PICKUP = 'PICKUP',
  DELIVERY = 'DELIVERY',
}

export enum DonationType {
  FOOD = 'FOOD',
  FINANCIAL = 'FINANCIAL',
}

export enum DonationStatus {
  PENDING = 'PENDING',
  SCHEDULED = 'SCHEDULED',
  COLLECTED = 'COLLECTED',
  DISTRIBUTED = 'DISTRIBUTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}

export enum AdFormat {
  BANNER = 'BANNER',
  CARD = 'CARD',
  INTERSTITIAL = 'INTERSTITIAL',
}

export enum NotificationType {
  // Order lifecycle
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_PAID = 'ORDER_PAID',
  ORDER_PREPARING = 'ORDER_PREPARING',
  ORDER_READY = 'ORDER_READY',
  ORDER_IN_DELIVERY = 'ORDER_IN_DELIVERY',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_REFUNDED = 'ORDER_REFUNDED',

  // Payment & Escrow
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  ESCROW_RELEASED = 'ESCROW_RELEASED',
  ESCROW_DISPUTED = 'ESCROW_DISPUTED',
  PAYOUT_FAILED = 'PAYOUT_FAILED',

  // Products
  NEW_PRODUCT_NEARBY = 'NEW_PRODUCT_NEARBY',
  PRODUCT_EXPIRING_SOON = 'PRODUCT_EXPIRING_SOON',

  // Donations
  DONATION_CONFIRMED = 'DONATION_CONFIRMED',

  // Subscriptions & Deals
  SUBSCRIPTION_EXPIRING = 'SUBSCRIPTION_EXPIRING',
  DEAL_BOOKING_CONFIRMED = 'DEAL_BOOKING_CONFIRMED',
  DEAL_BOOKING_REMINDER = 'DEAL_BOOKING_REMINDER',

  // Campaigns & System
  CAMPAIGN_APPROVED = 'CAMPAIGN_APPROVED',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  PROMOTION_ALERT = 'PROMOTION_ALERT',
  WELCOME = 'WELCOME',
}

export enum NotificationPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum DeviceType {
  IOS = 'IOS',
  ANDROID = 'ANDROID',
  WEB = 'WEB',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  MOBILE_MONEY = 'mobile_money',
  CARD = 'card',
  CASH = 'cash',
}

export enum MobileMoneyProvider {
  ORANGE_MONEY = 'orange_money',
  MTN_MONEY = 'mtn_money',
  MOOV_MONEY = 'moov_money',
  WAVE = 'wave',
}

export enum CardProvider {
  STRIPE = 'stripe',
  PAYSTACK = 'paystack',
}
